providers = ["node"]

[variables]
NIXPACKS_NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["...", "python3", "ffmpeg", "yt-dlp"]

[phases.install]
cmds = [
  "pnpm install --frozen-lockfile"
]

[start]
cmd = "node index.js"
