providers = ["node"]

[variables]
NIXPACKS_NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["...", "python3", "ffmpeg"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile --prod=false","python3 -m pip install yt-dlp"]

[start]
cmd = "node index.js"
