providers = ["node"]

[variables]
NIXPACKS_NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["...", "python3", "ffmpeg", "yt-dlp"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@9 --activate",
  "pnpm install --no-frozen-lockfile"
]

[start]
cmd = "node index.js"
